export const HAT_DATA = [
    {
        id: 'mu-luoi-trai-nam-1',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product0.jpg',
        ratting: 3,
        countOfRatting: 2,
        to: '/product/mu-luoi-trai-nam-1',
    },
    {
        id: 'mu-luoi-trai-nam-2',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product1.jpg ',
        ratting: 3,
        countOfRatting: 2,
        to: '/product/mu-luoi-trai-nam-2',
    },
    {
        id: 'mu-luoi-trai-nam-3',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product2.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/mu-luoi-trai-nam-3',
    },
    {
        id: 'mu-luoi-trai-nam-4',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product3.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/mu-luoi-trai-nam-4',
    },
    {
        id: 'mu-luoi-trai-nam-5',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product4.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/mu-luoi-trai-nam-5',
    },
    {
        id: 'mu-luoi-trai-nam-6',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product5.jpg ',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/mu-luoi-trai-nam-6',
    },
    {
        id: 'mu-luoi-trai-1',
        nameProduct: 'Mũ/Nón lưỡi trai nam Classic Cap thêu logo Coolmate - Xanh lá',
        price: 199000,
        image: '/assets/imageProduct/product6.jpg ',
        ratting: 4.8,
        countOfRatting: 10,
        to: '/product/mu-luoi-trai-1',
        features: [
            'Chất liệu 65% Cotton, 35% Polyester',
            'Thiết kế độc đáo được thêu phía trước mũ nổi bật',
            'Phù hợp với: mọi hoạt động hàng ngày',
            'Vành hẹp: Chu vi mũ 60cm',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
];

export const NIKE_DATA = [
    {
        id: 'giay-nike-1',
        nameProduct: 'Giày Nike Giày Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product7.jpg ',
        ratting: 3,
        countOfRatting: 100,
        to: '/product/giay-nike-1',
        features: [
            'Nike Air Force 1 Low LE GS All White – “cầu nối” giữa quá khứ và hiện tại. Những giá trị lâu đời của dòng giày Air Force 1 được thể hiện rõ ràng ở bộ đế: họa tiết sao năm cánh dập nổi, những vòng tròn đồng tâm giúp tăng độ bám (traction) và công nghệ đế Air danh tiếng từ những năm 1979. Mặt khác, đôi giày mang đến cảm giác tươi mới với cổ thấp, tông màu trắng tối giản két hợp cùng những đường nét cắt xẻ hiện đại ở phần upper. Quá tuyệt vời cho một đôi giày đa dụng phải không? Ghé Dee Store để sở hữu ngay một đôi nhé!',
        ],
    },
    {
        id: 'giay-nike-2',
        nameProduct: 'Giày Nike Giày Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product8.jpg ',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/giay-nike-2',
    },
    {
        id: 'giay-nike-3',
        nameProduct: 'Giày Nike Giày Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product9.jpg ',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/giay-nike-3',
    },
    {
        id: 'giay-nike-4',
        nameProduct: 'Giày Nike Giày Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product10.jpg',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/giay-nike-4',
    },
    {
        id: 'giay-nike-5',
        nameProduct: 'Giày Nike Giày Nike Air Force 1 Low LE GS All White DH2920-111',
        price: 2000000,
        image: '/assets/imageProduct/product11.jpg',
        ratting: 2,
        countOfRatting: 100,
        to: '/product/giay-nike-5',
    },
];

export const ADIDAS_DATA = [
    {
        id: 'giay-adidas-1',
        nameProduct: 'Giày Thể Thao Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product12.jpg',
        ratting: 5,
        countOfRatting: 100,
        to: '/product/giay-adidas-1',
        features: [
            'Thiết kế tối ưu cho việc vận động, mũi giày bo tròn, thon gọn, tạo cảm giác mềm mại, vừa vặn, thoải mái cho bàn chân.',
            'Chống cong chân, chống va chạm với gót chân, giảm chấn thương, tăng sức bật.',
            'Sử dụng công nghệ cao trong sản xuất với những vật liệu chất lượng cao giúp cho giày có độ bền vượt thời gian.',
            'Các thiết kế không chỉ phục vụ cho thể thao mà còn hướng đến yếu tố thời trang và phong cách.',
            'Dễ dàng phối hợp với các trang phục',
            'Không phân biệt giới tính về kiểu dáng,  cả nam và nữ khi mang giày Adidas chính hãng đều tôn lên sự trẻ trung, năng động và thể hiện phong cách thời trang của chính mình.',
        ],
    },
    {
        id: 'giay-adidas-2',
        nameProduct: 'Giày Thể Thao Adidas Neo Grand Court K EF0103',
        price: 2133000,
        image: '/assets/imageProduct/product13.jpg',
        ratting: 5,
        countOfRatting: '1.000',
        to: '/product/giay-adidas-2',
    },
    {
        id: 'giay-adidas-3',
        nameProduct: 'Giày Thể Thao Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product14.jpg',
        ratting: 2,
        countOfRatting: 32,
        to: '/product/giay-adidas-4',
    },
    {
        id: 'giay-adidas-4',
        nameProduct: 'Giày Thể Thao Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product15.jpg',
        ratting: 5,
        countOfRatting: 32,
        to: '/product/giay-adidas-4',
    },
    {
        id: 'giay-adidas-5',
        nameProduct: 'Giày Thể Thao Adidas Neo Grand Court K EF0103',
        price: 2000000,
        image: '/assets/imageProduct/product16.jpg',
        ratting: 5,
        countOfRatting: 132,
        to: '/product/giay-adidas-5',
    },
    {
        id: 'giay-adidas-6',
        nameProduct: 'Giày Thể Thao Adidas Neo Grand Court K EF0103',
        price: 321244,
        image: '/assets/imageProduct/product17.jpg',
        ratting: 4.5,
        countOfRatting: 100,
        to: '/product/giay-adidas-6',
    },
];

export const VANS_DATA = [
    {
        id: 'giay-vans-1',
        nameProduct: 'GIÀY THỂ THAO VANS AUTHENTIC BLACK/WHITE MÀU ĐEN',
        price: 1290000,
        image: '/assets/imageProduct/product18.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/giay-vans-1',
        features: [
            'Form giày Vans đi lên chân vừa vặn, các đường chỉ khâu vô cùng chắc chắn và tỉ mỉ đảm bảo hài lòng mọi khách hàng.',
            'Giày Thể Thao Vans Authentic Black/White Màu Đen màu sắc trắng dễ dàng kết hợp với nhiều trang phục khác nhau theo sở thích bản thân tạo nên 1 set đồ đẹp khi đi chơi, đi học hay dạo phố...',
            'Với kiểu dáng Style trẻ trung, đẹp mắt, mang đậm phong cách, cá tính cho người mang. Phần đế giày có độ ma sát cao hạn chế trơn trượt cho người sử dụng.',
            'Không chỉ dành cho người yêu sneaker, đôi giày còn phù hợp với những tín đồ đam mê thể thao với phong cách thời trang năng động, đậm nét cá tính.',
        ],
    },
    {
        id: 'giay-vans-2',
        nameProduct: 'GIÀY THỂ THAO VANS AUTHENTIC BLACK/WHITE MÀU ĐEN',
        price: 1290000,
        image: '/assets/imageProduct/product19.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/giay-vans-2',
        features: [
            'Form giày Vans đi lên chân vừa vặn, các đường chỉ khâu vô cùng chắc chắn và tỉ mỉ đảm bảo hài lòng mọi khách hàng.',
            'Giày Thể Thao Vans Authentic Black/White Màu Đen màu sắc trắng dễ dàng kết hợp với nhiều trang phục khác nhau theo sở thích bản thân tạo nên 1 set đồ đẹp khi đi chơi, đi học hay dạo phố...',
            'Với kiểu dáng Style trẻ trung, đẹp mắt, mang đậm phong cách, cá tính cho người mang. Phần đế giày có độ ma sát cao hạn chế trơn trượt cho người sử dụng.',
            'Không chỉ dành cho người yêu sneaker, đôi giày còn phù hợp với những tín đồ đam mê thể thao với phong cách thời trang năng động, đậm nét cá tính.',
        ],
    },
    {
        id: 'giay-vans-3',
        nameProduct: 'GIÀY THỂ THAO VANS AUTHENTIC BLACK/WHITE MÀU ĐEN',
        price: 1290000,
        image: '/assets/imageProduct/product20.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/giay-vans-3',
        features: [
            'Form giày Vans đi lên chân vừa vặn, các đường chỉ khâu vô cùng chắc chắn và tỉ mỉ đảm bảo hài lòng mọi khách hàng.',
            'Giày Thể Thao Vans Authentic Black/White Màu Đen màu sắc trắng dễ dàng kết hợp với nhiều trang phục khác nhau theo sở thích bản thân tạo nên 1 set đồ đẹp khi đi chơi, đi học hay dạo phố...',
            'Với kiểu dáng Style trẻ trung, đẹp mắt, mang đậm phong cách, cá tính cho người mang. Phần đế giày có độ ma sát cao hạn chế trơn trượt cho người sử dụng.',
            'Không chỉ dành cho người yêu sneaker, đôi giày còn phù hợp với những tín đồ đam mê thể thao với phong cách thời trang năng động, đậm nét cá tính.',
        ],
    },
    {
        id: 'giay-vans-4',
        nameProduct: 'GIÀY THỂ THAO VANS AUTHENTIC BLACK/WHITE MÀU ĐEN',
        price: 1290000,
        image: '/assets/imageProduct/product21.jpg',
        ratting: 4,
        countOfRatting: 213,
        to: '/product/giay-vans-4',
        features: [
            'Form giày Vans đi lên chân vừa vặn, các đường chỉ khâu vô cùng chắc chắn và tỉ mỉ đảm bảo hài lòng mọi khách hàng.',
            'Giày Thể Thao Vans Authentic Black/White Màu Đen màu sắc trắng dễ dàng kết hợp với nhiều trang phục khác nhau theo sở thích bản thân tạo nên 1 set đồ đẹp khi đi chơi, đi học hay dạo phố...',
            'Với kiểu dáng Style trẻ trung, đẹp mắt, mang đậm phong cách, cá tính cho người mang. Phần đế giày có độ ma sát cao hạn chế trơn trượt cho người sử dụng.',
            'Không chỉ dành cho người yêu sneaker, đôi giày còn phù hợp với những tín đồ đam mê thể thao với phong cách thời trang năng động, đậm nét cá tính.',
        ],
    },
];

export const MLB_DATA = [
    {
        id: 'giay-mlb-1',
        nameProduct: 'Giày sneakers unisex Big Ball Chunky Cookie',
        price: 2990000,
        image: '/assets/imageProduct/product22.jpg',
        ratting: 4.8,
        countOfRatting: 282,
        to: '/product/giay-mlb-1',
        features: [
            'Kiểu dáng giày sneakers đế cao thời trang',
            'Thiết kế lấy cảm hứng từ hiệp hội bóng chày MLB',
            'Cộng hưởng cùng chi tiết chữ logo bóng chày sắc nét',
            'Kết hợp đan xen giữa chất liệu da cao cấp với lớp lưới upper thoáng khí',
            'Lớp lót êm ái, nâng dáng bước chân',
            'Gam màu hiện đại dễ dàng phối với nhiều trang phục và phụ kiện',
            'Xuất xứ thương hiệu: Hàn Quốc',
        ],
    },
    {
        id: 'giay-mlb-2',
        nameProduct: 'Giày sneakers unisex Big Ball Chunky Cookie',
        price: 2990000,
        image: '/assets/imageProduct/product23.jpg',
        ratting: 4.2,
        countOfRatting: 1312,
        to: '/product/giay-mlb-2',
        features: [
            'Kiểu dáng giày sneakers đế cao thời trang',
            'Thiết kế lấy cảm hứng từ hiệp hội bóng chày MLB',
            'Cộng hưởng cùng chi tiết chữ logo bóng chày sắc nét',
            'Kết hợp đan xen giữa chất liệu da cao cấp với lớp lưới upper thoáng khí',
            'Lớp lót êm ái, nâng dáng bước chân',
            'Gam màu hiện đại dễ dàng phối với nhiều trang phục và phụ kiện',
            'Xuất xứ thương hiệu: Hàn Quốc',
        ],
    },
    {
        id: 'giay-mlb-3',
        nameProduct: 'Giày sneakers unisex Big Ball Chunky Cookie',
        price: 2990000,
        image: '/assets/imageProduct/product24.jpg',
        ratting: 4.2,
        countOfRatting: 1312,
        to: '/product/giay-mlb-3',
        features: [
            'Kiểu dáng giày sneakers đế cao thời trang',
            'Thiết kế lấy cảm hứng từ hiệp hội bóng chày MLB',
            'Cộng hưởng cùng chi tiết chữ logo bóng chày sắc nét',
            'Kết hợp đan xen giữa chất liệu da cao cấp với lớp lưới upper thoáng khí',
            'Lớp lót êm ái, nâng dáng bước chân',
            'Gam màu hiện đại dễ dàng phối với nhiều trang phục và phụ kiện',
            'Xuất xứ thương hiệu: Hàn Quốc',
        ],
    },
];

export const SHOES_DATA = [...NIKE_DATA, ...ADIDAS_DATA, ...VANS_DATA, ...MLB_DATA];

export const MENS_SHIRT = [];

export const T_SHIRT = [
    {
        id: 'ao-thun-1',
        nameProduct: 'Áo thun thể thao nam Recycle Active V2',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product25.jpg',
        ratting: 1,
        countOfRatting: 2,
        to: '/product/ao-thun-1',
        features: [
            'Chất liệu: 100% Recycle Polyester với định lượng vải 140gsm siêu nhẹ',
            'Phù hợp với: chơi thể thao',
            'Kiểu dáng: áo thun thể thao vừa vặn với dáng nam giới Việt Nam',
            'Công nghệ ứng dụng: Wicking (thoáng khí) & Quick-Dry (Nhanh khô)',
            'Nhà cung cấp vải hàng đầu thế giới trong lĩnh vực đồ thể thao: Promax',
            'Tự hào may và hoàn thiện tại nhà máy Nobland, Bình Dương',
        ],
    },
    {
        id: 'ao-thun-2',
        nameProduct: 'Áo thun Marvel Avengers Logo Basics - Cacao',
        price: 299000,
        priceOld: 299000,
        imageHover:
            'https://media.coolmate.me/cdn-cgi/image/width=672,height=990,quality=85,format=auto/uploads/August2022/cacao_aven_8.jpg',
        image: '/assets/imageProduct/product26.jpg',
        ratting: 2,
        countOfRatting: 3,
        to: '/product/ao-thun-2',
        features: [
            'Chất liệu: 80% Cotton - 20% Recycle Polyester, co giãn 4 chiều',
            'Là sản phẩm của sự hợp tác giữa Coolmate và Disney - đơn vị sở hữu bản quyền Marvel',
            'Phù hợp với: đi làm, đi chơi, ở nhà',
            'Kiểu dáng: regularfit dáng suông',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
    {
        id: 'ao-thun-3',
        nameProduct: 'Áo thun thể thao nam Recycle Active V2',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product27.jpg',
        ratting: 5,
        countOfRatting: 2,
        to: '/product/ao-thun-3',
        features: [
            'Chất liệu: 100% Recycle Polyester với định lượng vải 140gsm siêu nhẹ',
            'Phù hợp với: chơi thể thao',
            'Kiểu dáng: áo thun thể thao vừa vặn với dáng nam giới Việt Nam',
            'Công nghệ ứng dụng: Wicking (thoáng khí) & Quick-Dry (Nhanh khô)',
            'Nhà cung cấp vải hàng đầu thế giới trong lĩnh vực đồ thể thao: Promax',
            'Tự hào may và hoàn thiện tại nhà máy Nobland, Bình Dương',
        ],
    },
    {
        id: 'ao-thun-4',
        nameProduct: 'Áo thun Marvel Avengers Logo Basics - Cacao',
        price: 299000,
        priceOld: 299000,
        image: '/assets/imageProduct/product28.jpg',
        ratting: 5,
        countOfRatting: 3,
        to: '/product/ao-thun-4',
        features: [
            'Chất liệu: 80% Cotton - 20% Recycle Polyester, co giãn 4 chiều',
            'Là sản phẩm của sự hợp tác giữa Coolmate và Disney - đơn vị sở hữu bản quyền Marvel',
            'Phù hợp với: đi làm, đi chơi, ở nhà',
            'Kiểu dáng: regularfit dáng suông',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
];

export const SHIRT = [
    {
        id: 'ao-so-mi-1',
        nameProduct: 'Áo sơ mi nam dài tay Café-DriS khử mùi hiệu quả',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product29.jpg',
        ratting: 4.9,
        countOfRatting: 160,
        to: '/product/ao-so-mi-1',
        features: [
            'Chất liệu: 50% Café - 50% Recycled Poly from PET đem đến sự mềm mại và khử mùi hiệu quả',
            'Phù hợp với: đi làm, đi chơi',
            'Kiểu dáng: regularfit dáng suông',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
    {
        id: 'ao-so-mi-2',
        nameProduct: 'Áo Sơ mi nam Excool Limited ngắn tay chui đầu',
        price: 259000,
        priceOld: 299000,
        image: '/assets/imageProduct/product30.jpg',
        ratting: 4.5,
        countOfRatting: 17,
        to: '/product/ao-so-mi-2',
        features: [
            'Chất liệu: 53% Polyester PET high stretch + 47% Polyester PTT Sorona',
            'Phù hợp với: đi chơi, đi làm, tham gia hoạt động lịch sự',
            'Kiểu dáng: regularfit dáng suông',
            'Đây là mẫu sơ mi phong cách Nhật lần đầu tiên tại Coolmate',
            'Tự hào may và hoàn thiện tại nhà máy Nobland, Bình Dương',
        ],
    },
    {
        id: 'ao-so-mi-3',
        nameProduct: 'Áo sơ mi nam dài tay Café-DriS khử mùi hiệu quả',
        price: 159000,
        priceOld: 299000,
        image: '/assets/imageProduct/product31.jpg',
        ratting: 4.9,
        countOfRatting: 160,
        to: '/product/ao-so-mi-3',
        features: [
            'Chất liệu: 50% Café - 50% Recycled Poly from PET đem đến sự mềm mại và khử mùi hiệu quả',
            'Phù hợp với: đi làm, đi chơi',
            'Kiểu dáng: regularfit dáng suông',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
    {
        id: 'ao-so-mi-4',
        nameProduct: 'Áo Sơ mi nam Excool Limited ngắn tay chui đầu',
        price: 259000,
        priceOld: 299000,
        image: '/assets/imageProduct/product32.jpg',
        ratting: 4.5,
        countOfRatting: 17,
        to: '/product/ao-so-mi-4',
        features: [
            'Chất liệu: 53% Polyester PET high stretch + 47% Polyester PTT Sorona',
            'Phù hợp với: đi chơi, đi làm, tham gia hoạt động lịch sự',
            'Kiểu dáng: regularfit dáng suông',
            'Đây là mẫu sơ mi phong cách Nhật lần đầu tiên tại Coolmate',
            'Tự hào may và hoàn thiện tại nhà máy Nobland, Bình Dương',
        ],
    },
];

export const POLO_SHIRT = [
    {
        id: 'ao-polo-1',
        nameProduct: 'Áo Polo nam Café - khử mùi hiệu quả',
        price: 239000,
        priceOld: 299000,
        image: '/assets/imageProduct/product33.jpg',
        ratting: 4.9,
        countOfRatting: 95,
        to: '/product/ao-polo-1',
        features: [
            'Chất liệu: 50% S.Café + 50% Recycled PET, đem đến sự mềm mại và khử mùi hiệu quả',
            'Công nghệ ứng dụng: Hydroponic tăng khả năng bốc hơi nước khỏi vải, giúp nhanh khô',
            'Phù hợp với: đi làm, đi chơi, mặc ở nhà',
            'Kiểu dáng: regularfit dáng suông',
            'Phần bo cổ sản xuất tại nhà máy chất lượng cao, sử dụng sợi Hightwisted 45D/75D tạo co giãn và bền form',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
    {
        id: 'ao-polo-2',
        nameProduct: 'Áo Polo nam Café - khử mùi hiệu quả',
        price: 239000,
        image: '/assets/imageProduct/product34.jpg',
        ratting: 4.9,
        countOfRatting: 95,
        to: '/product/ao-polo-2',
        features: [
            'Chất liệu: 50% S.Café + 50% Recycled PET, đem đến sự mềm mại và khử mùi hiệu quả',
            'Công nghệ ứng dụng: Hydroponic tăng khả năng bốc hơi nước khỏi vải, giúp nhanh khô',
            'Phù hợp với: đi làm, đi chơi, mặc ở nhà',
            'Kiểu dáng: regularfit dáng suông',
            'Phần bo cổ sản xuất tại nhà máy chất lượng cao, sử dụng sợi Hightwisted 45D/75D tạo co giãn và bền form',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
];

export const SPORTS_SHIRT = [
    {
        id: 'ao-the-thao-1',
        nameProduct: 'Áo Tank top thể thao nam thoáng khí',
        price: 99000,
        image: '/assets/imageProduct/product35.jpg',
        ratting: 4.5,
        countOfRatting: 209,
        to: '/product/ao-the-thao-1',
        features: [
            'Chất liệu: 100% Polyester tính năng Quick Dry (Nhanh Khô)',
            'Kiểu dệt Twill (chéo) mới mang lại cảm giác thoải mái khi mặc',
            'Phù hợp với: đi chơi, đi làm, mặc ở nhà',
            'Kiểu dáng: regularfit dáng suông',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
    {
        id: 'ao-the-thao-2',
        nameProduct: 'Áo thun thể thao nam ProMax-S1',
        price: 149000,
        image: '/assets/imageProduct/product36.jpg',
        ratting: 4.5,
        countOfRatting: 94,
        to: '/product/ao-the-thao-2',
        features: [
            'Chất liệu: 100% Polyester',
            'Công nghệ xử lý hoàn thiện vải: Quick-Dry (nhanh khô) và Wicking (thấm hút nhanh)',
            'Phù hợp với: chơi thể thao',
            'Kiểu dáng: regularfit dáng suông',
            'Tự hào may và hoàn thiện tại nhà máy Nobland, Bình Dương',
        ],
    },
];

export const COAT = [
    {
        id: 'ao-khoac-1',
        nameProduct: 'Áo khoác gió thể thao HeiQ ViroBlock, chống UV & trượt nước',
        price: 449000,
        image: '/assets/imageProduct/product37.jpg',
        ratting: 4.8,
        countOfRatting: 340,
        to: '/product/ao-khoac-1',
        features: [
            'SẢN PHẨM CÓ THỂ ĐƯỢC TẶNG KÈM MẶT NẠ CHỐNG GIỌT BẮN',
            'Chất liệu: Polyester',
            'Công nghệ ứng dụng: HeiQ ViroBlock có khả năng diệt 99.99% SARS-CoV2 trong vòng 30p',
            'Phù hợp với: áo chống nắng, tránh gió',
            'Áo có khả năng chống tia UV',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
    {
        id: 'ao-khoac-2',
        nameProduct: 'Áo khoác nam có mũ Daily Wear - trượt nước, chống UV 99%',
        price: 449000,
        image: '/assets/imageProduct/product38.jpg',
        ratting: 4.8,
        countOfRatting: 17,
        to: '/product/ao-khoac-2',
        features: [
            'Chất liệu 100% Polyester',
            'Công nghệ ứng dụng: HeiQ Viro Block',
            'Phù hợp với: khoác ngoài chống nắng, tránh gió',
            'Kiểu dáng: nhỏ gọn, dễ mặc',
            'Tự hào sản xuất tại Việt Nam',
        ],
    },
];

export const SHIRTS = [...MENS_SHIRT, ...T_SHIRT, ...SHIRT, ...POLO_SHIRT, ...SPORTS_SHIRT, ...COAT];

export const PRODUCTS = [...SHIRTS, ...HAT_DATA, ...SHOES_DATA];

export const COLOR_SHIRTS = ['white', 'black', 'gray', 'blue', 'yellow']
